[package]
name = "player_one_nvim"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.10.2", features = ["lua54", "module","serialize"] }
rodio = "0.20.1"
